# Generated by Django 2.2 on 2019-06-12 16:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('cred', '0003_upgrade_to_django22'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('icon', models.BinaryField(default=None, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cred',
            name='descriptionmarkdown',
        ),
        migrations.RemoveField(
            model_name='cred',
            name='iconname',
        ),
        migrations.RemoveField(
            model_name='cred',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='cred',
            name='attachment_name',
        ),
        migrations.RemoveField(
            model_name='cred',
            name='ssh_key',
        ),
        migrations.RemoveField(
            model_name='cred',
            name='ssh_key_name',
        ),
        migrations.AddField(
            model_name='attachment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cred',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='cred',
            name='project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='cred.Project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='credaudit',
            name='audittype',
            field=models.CharField(choices=[('A', 'Added'), ('C', 'Changed'), ('M', 'Only Metadata Changed'), ('V', 'Only Details Viewed'), ('X', 'Exported'), ('D', 'Deleted'), ('R', 'Restored'), ('S', 'Scheduled For Change'), ('P', 'Password Viewed'), ('AD', 'Attachment Added'), ('AV', 'Attachment Viewed'), ('AD', 'Attachment Deleted')], max_length=5),
        ),
        migrations.AlterField(
            model_name='project',
            name='icon',
            field=models.BinaryField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(db_index=True, max_length=128, unique=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='cred',
            name='icon',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='cred.CredentialIcon', verbose_name='Icon'),
        ),
    ]
