# Generated by Django 2.2 on 2019-04-27 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cred', '0003_upgrade_to_django22'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credaudit',
            name='audittype',
            field=models.CharField(choices=[('A', 'Added'), ('C', 'Changed'), ('M', 'Only Metadata Changed'), ('V', 'Only Details Viewed'), ('X', 'Exported'), ('D', 'Deleted'), ('R', 'Restored'), ('S', 'Scheduled For Change'), ('P', 'Password Viewed'), ('AD', 'Attachment Added'), ('AV', 'Attachment Viewed'), ('AD', 'Attachment Deleted')], max_length=5),
        ),
    ]
