# Generated by Django 2.2 on 2019-05-13 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cred', '0003_upgrade_to_django22'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='cred',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='cred',
            name='project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='cred.Project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='credaudit',
            name='audittype',
            field=models.CharField(choices=[('A', 'Added'), ('C', 'Changed'), ('M', 'Only Metadata Changed'), ('V', 'Only Details Viewed'), ('X', 'Exported'), ('D', 'Deleted'), ('R', 'Restored'), ('S', 'Scheduled For Change'), ('P', 'Password Viewed'), ('AD', 'Attachment Added'), ('AV', 'Attachment Viewed'), ('AD', 'Attachment Deleted')], max_length=5),
        ),
    ]
