# Generated by Django 2.2 on 2019-05-12 16:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cred', '0004_auto_20190512_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cred',
            name='groups',
            field=models.ManyToManyField(blank=True, default=None, related_name='child_creds', to='auth.Group', verbose_name='Groups'),
        ),
        migrations.AlterField(
            model_name='cred',
            name='tags',
            field=models.ManyToManyField(blank=True, default=None, related_name='child_creds', to='cred.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='cred',
            name='users',
            field=models.ManyToManyField(blank=True, default=None, related_name='child_creds', to=settings.AUTH_USER_MODEL, verbose_name='Users'),
        ),
    ]
