# Generated by Django 2.2 on 2019-04-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cred', '0004_auto_20190427_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
