# Generated by Django 2.2 on 2019-05-11 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cred', '0005_attachment_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cred',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='cred.Project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='credaudit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credlogs', to=settings.AUTH_USER_MODEL),
        ),
    ]
