# Generated by Django 2.2 on 2019-05-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cred', '0006_project_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='icon',
            field=models.BinaryField(default=None, null=True),
        ),
    ]
