# Generated by Django 2.2 on 2019-05-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cred', '0007_auto_20190522_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
