# Generated by Django 2.2 on 2019-05-25 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cred', '0008_auto_20190523_0124'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('icon', models.BinaryField(default=None, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cred',
            name='iconname',
        ),
        migrations.AddField(
            model_name='cred',
            name='icon',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='cred.CredentialIcon', verbose_name='Icon'),
        ),
    ]
