# Generated by Django 2.2 on 2019-05-25 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cred', '0009_auto_20190525_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cred',
            name='descriptionmarkdown',
        ),
    ]
