# Generated by Django 2.2 on 2019-05-25 06:33

from django.db import migrations

def create_credential_icons(apps, schema_editor):
    'Create initial credentials icon set'
    CredentialIcon = apps.get_model('cred', 'CredentialIcon')

    


class Migration(migrations.Migration):

    dependencies = [
        ('cred', '0010_remove_cred_descriptionmarkdown'),
    ]

    operations = [
        migrations.RunPython(create_credential_icons),
    ]
