# Generated by Django 2.2 on 2019-04-20 07:22

from django.db import migrations, models
from django.conf import settings
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cred', '0003_upgrade_to_django22'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('name', models.CharField(blank=True, default='unknown', max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rattic_api_key', to=settings.AUTH_USER_MODEL)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('items_per_page', models.IntegerField(default=25, verbose_name='Items per page')),
                ('password_changed', models.DateTimeField(default=django.utils.timezone.now)),
                ('favourite_tags', models.ManyToManyField(blank=True, to='cred.Tag', verbose_name='Favourite tags')),
            ],
        ),
    ]
