# Generated by Django 2.2 on 2019-05-12 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_upgrade_to_django22'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.BinaryField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favourite_menu',
            field=models.BooleanField(default=True, verbose_name='Enable favorites menu'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='theme',
            field=models.CharField(default='bootstrap.default.min.css', max_length=128, verbose_name='Theme'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rattic_api_key', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='items_per_page',
            field=models.IntegerField(default=25, verbose_name='Items at page'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
