# Generated by Django 2.2 on 2019-05-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_upgrade_to_django22'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.BinaryField(default=None, null=True),
        ),
    ]
