# Generated by Django 2.2.4 on 2019-09-01 11:38

from django.db import migrations, models, connection

def drop_user_session_table(apps, schema_editor):
    """
    Drop legacy table from django-user-session app
    """

    connection.cursor().execute("DROP TABLE IF EXISTS user_sessions_session;")



class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_upgrade_to_boostrap'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='session key')),
                ('session_data', models.TextField(verbose_name='session data')),
                ('expire_date', models.DateTimeField(db_index=True, verbose_name='expire date')),
                ('user_id', models.IntegerField(db_index=True, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('ip', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'verbose_name': 'session',
                'verbose_name_plural': 'sessions',
                'abstract': False,
            },
        ),
        migrations.RunPython(drop_user_session_table),
    ]
