# Generated by Django 2.2 on 2019-05-25 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190514_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='favourite_menu',
        ),
    ]
