# Generated by Django 2.2 on 2019-05-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cred', '0005_auto_20190513_0239'),
        ('account', '0003_auto_20190512_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favourite_credentials',
            field=models.ManyToManyField(blank=True, to='cred.Cred', verbose_name='Favourite credentials'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favourite_projects',
            field=models.ManyToManyField(blank=True, to='cred.Project', verbose_name='Favourite projects'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.BinaryField(default=None, null=True, verbose_name='Profile avatar'),
        ),
    ]
