# Generated by Django 2.2 on 2019-05-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favourite_menu',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='theme',
            field=models.CharField(default='default', max_length=128),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='items_per_page',
            field=models.IntegerField(default=25, verbose_name='Items at page'),
        ),
    ]
