# Generated by Django 2.2 on 2019-05-11 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20190503_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='favourite_menu',
            field=models.BooleanField(default=False, verbose_name='Enable favorites menu'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='theme',
            field=models.CharField(default='bootstrap.default.min.css', max_length=128, verbose_name='Theme'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
